
# today_date_and_time = datetime.now()
def write_sales(name,phone,date_time,sold_laptop,shippingcost,total_price,total):
    with open(str(name) + str(phone) +".txt", "w")as file:
        file.write("\n")
        file.write("\t \t \t \t Utsav's Laptop Shop")
        file.write("\n")
        file.write("\t \t Kamalpokhari, Kathmandu | Phone No: 9862414547 ")
        file.write("\n")
        file.write("****************************************************************************************\n")
        file.write("\n")
        file.write("Laptop Details: ")
        file.write("\n")
        file.write("******************\n")
        file.write("Customer Name:" + str(name))
        file.write("\n")
        file.write("Phone Number: " + str(phone))
        file.write("\n")
        file.write("Date and Time: " + str(date_time))
        file.write("\n")
        file.write("****************************************************************************************\n")
        file.write("\n")
        file.write("Purchase Details are:")
        file.write("\n")
        file.write("***************************************************************************************************\n")
        file.write("Product Name \t\t Total Quantity \t\t Unit Price \t\t Total")
        file.write("\n")
        file.write("***************************************************************************************************\n")
        for i in sold_laptop:
            file.write(str(i[0]) + "\t\t\t" + str(i[1]) + "\t\t\t" + str(i[2]) + "\t\t\t" + "$" + str(i[3])+"\n")
        file.write("***************************************************************************************************\n")
        file.write("\n")
        if shippingcost:
            file.write("Shipping Cost:" +""+ str(shippingcost)+ "\n")
            file.write("\n")
            file.write("Grand Total: $" + str(total_price)+ "\n")
            file.write("\n")
            file.write("Note: Shipping Cost added to grand total" + "\n")
        else:
            file.write("Your total price is: $" + str(total)+"\n")
            file.write("Your shipping cost is: $" + str(shippingcost)+"\n")
            file.write("Grand Total: $" + str(total)+"\n")


def write_purchase(name,phone,date_time,purchase_laptop,VAT,total_price):
    with open(str(name) + str(phone) +".txt", "w")as file:
        file.write("\n")
        file.write("\t \t \t \t Utsav's Laptop Shop")
        file.write("\n")
        file.write("\t \t Kamalpokhari, Kathmandu | Phone No: 9862414547 ")
        file.write("\n")
        file.write("****************************************************************************************\n")
        file.write("Laptop Details: ")
        file.write("\n")
        file.write("*******************\n")
        file.write("Customer Name:" + str(name))
        file.write("\n")
        file.write("Phone Number: " + str(phone))
        file.write("\n")
        file.write("Date and Time: " + str(date_time))
        file.write("\n")
        file.write("****************************************************************************************\n")
        file.write("\n")
        file.write("Purchase Details are:")
        file.write("\n")
        file.write("***************************************************************************************************\n")
        file.write("Product Name \t\t Total Quantity \t\t Unit Price \t\t Total")
        file.write("\n")
        file.write("***************************************************************************************************\n")
        for i in purchase_laptop:
            file.write(str(i[0]) + "\t\t\t" + str(i[1]) + "\t\t\t" + str(i[2]) + "\t\t\t" + "$" + str(i[3])+"\n")
        file.write("***************************************************************************************************\n")
        file.write("\n")
        if VAT:
            file.write("Vat Amount:" +""+ str(VAT)+ "\n")
            file.write("\n")
            file.write("Grand Total: $" + str(total_price)+ "\n")
            file.write("\n")
            file.write("Note: Vat Amount added to grand total" + "\n")
            file.write("\n")
        else:
            file.write("Grand Total: $" + str(total_price))
